# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'courseme' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for courseme
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Database', '~>5.9.0'

  target 'courseme-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coursemeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'courseme-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for courseme-tvOS

end
